[project]
name = "langchain_to"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "ipykernel>=7.3.0",
    "langchain>=0.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.4.9",
    "langchain-openrouter>=0.2.6",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.2",
]
