-- Create Warehouse
CREATE WAREHOUSE METRICMIND_WH
WITH WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

-- Use Warehouse
USE WAREHOUSE METRICMIND_WH;

-- Create Database
CREATE DATABASE METRICMIND_DB;

-- Use Database
USE DATABASE METRICMIND_DB;

-- Create Schemas
CREATE SCHEMA RAW;
CREATE SCHEMA ANALYTICS;

-- Create Customers Table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    CREATED_DATE DATE
);

-- Create Products Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    BRAND STRING,
    UNIT_PRICE NUMBER(10,2),
    COST_PRICE NUMBER(10,2),
    STOCK_QUANTITY INT
);

-- Create Orders Table
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    PAYMENT_METHOD STRING,
    ORDER_STATUS STRING
);

-- Create Order Items Table
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INT PRIMARY KEY,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT NUMBER(5,2)
);