USE DATABASE METRICMIND_DB;
USE SCHEMA ANALYTICS;

COPY INTO CUSTOMERS
FROM @METRICMIND_DB.RAW.RAW_STAGE/customers.csv
FILE_FORMAT = (FORMAT_NAME = METRICMIND_DB.RAW.CSV_FORMAT);

COPY INTO ORDERS
FROM @METRICMIND_DB.RAW.RAW_STAGE/orders.csv
FILE_FORMAT = (FORMAT_NAME = METRICMIND_DB.RAW.CSV_FORMAT);

COPY INTO PRODUCTS
FROM @METRICMIND_DB.RAW.RAW_STAGE/products.csv
FILE_FORMAT = (FORMAT_NAME = METRICMIND_DB.RAW.CSV_FORMAT);

COPY INTO ORDER_ITEMS
FROM @METRICMIND_DB.RAW.RAW_STAGE/order_items.csv
FILE_FORMAT = (FORMAT_NAME = METRICMIND_DB.RAW.CSV_FORMAT);