USE DATABASE METRICMIND_DB;
USE SCHEMA ANALYTICS;

SELECT COUNT(*) AS CUSTOMER_COUNT
FROM CUSTOMERS;

SELECT COUNT(*) AS ORDER_COUNT
FROM ORDERS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM PRODUCTS;

SELECT COUNT(*) AS ORDER_ITEM_COUNT
FROM ORDER_ITEMS;